---
- jm1.pkg.meta_pkg:
    name: "jm1-dev-haskell"
    version: "1"
    depends:
    - haskell-platform

    # TODO: re-add package ghc-mod as soon as it supports GHC 8.2.1+
    # Ref.: https://github.com/DanielG/ghc-mod/issues/900
