---
- include_role:
    name: jm1.virtual_pkg
  vars:
    package_name: "jm1-dev-haskell"
    package_depends:
    - haskell-platform

    # TODO: re-add package ghc-mod as soon as it supports GHC 8.2.1+
    # Ref.: https://github.com/DanielG/ghc-mod/issues/900
